# TCL File Generated by Component Editor 18.1
# Fri Apr 02 18:22:20 MDT 2021
# DO NOT MODIFY


# 
# waveform_player "waveform_player" v2.0
#  2021.04.02.18:22:20
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module waveform_player
# 
set_module_property DESCRIPTION ""
set_module_property NAME waveform_player
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME waveform_player
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL waveform_player
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file waveform_player.sv SYSTEM_VERILOG PATH waveform_player.sv TOP_LEVEL_FILE
add_fileset_file doublesync.sv SYSTEM_VERILOG PATH doublesync.sv
add_fileset_file sdram_reader.sv SYSTEM_VERILOG PATH sdram_reader.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point HPS_avalon_slave
# 
add_interface HPS_avalon_slave avalon end
set_interface_property HPS_avalon_slave addressUnits WORDS
set_interface_property HPS_avalon_slave associatedClock clock
set_interface_property HPS_avalon_slave associatedReset reset
set_interface_property HPS_avalon_slave bitsPerSymbol 8
set_interface_property HPS_avalon_slave burstOnBurstBoundariesOnly false
set_interface_property HPS_avalon_slave burstcountUnits WORDS
set_interface_property HPS_avalon_slave explicitAddressSpan 0
set_interface_property HPS_avalon_slave holdTime 0
set_interface_property HPS_avalon_slave linewrapBursts false
set_interface_property HPS_avalon_slave maximumPendingReadTransactions 0
set_interface_property HPS_avalon_slave maximumPendingWriteTransactions 0
set_interface_property HPS_avalon_slave readLatency 0
set_interface_property HPS_avalon_slave readWaitTime 1
set_interface_property HPS_avalon_slave setupTime 0
set_interface_property HPS_avalon_slave timingUnits Cycles
set_interface_property HPS_avalon_slave writeWaitTime 0
set_interface_property HPS_avalon_slave ENABLED true
set_interface_property HPS_avalon_slave EXPORT_OF ""
set_interface_property HPS_avalon_slave PORT_NAME_MAP ""
set_interface_property HPS_avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property HPS_avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port HPS_avalon_slave address address Input 1
add_interface_port HPS_avalon_slave write write Input 1
add_interface_port HPS_avalon_slave writedata writedata Input 32
set_interface_assignment HPS_avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment HPS_avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment HPS_avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment HPS_avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point audio_clock
# 
add_interface audio_clock clock end
set_interface_property audio_clock clockRate 0
set_interface_property audio_clock ENABLED true
set_interface_property audio_clock EXPORT_OF ""
set_interface_property audio_clock PORT_NAME_MAP ""
set_interface_property audio_clock CMSIS_SVD_VARIABLES ""
set_interface_property audio_clock SVD_ADDRESS_GROUP ""

add_interface_port audio_clock audio_clock clk Input 1


# 
# connection point audio_reset
# 
add_interface audio_reset reset end
set_interface_property audio_reset associatedClock audio_clock
set_interface_property audio_reset synchronousEdges DEASSERT
set_interface_property audio_reset ENABLED true
set_interface_property audio_reset EXPORT_OF ""
set_interface_property audio_reset PORT_NAME_MAP ""
set_interface_property audio_reset CMSIS_SVD_VARIABLES ""
set_interface_property audio_reset SVD_ADDRESS_GROUP ""

add_interface_port audio_reset audio_reset reset Input 1


# 
# connection point l_audio_streaming_source
# 
add_interface l_audio_streaming_source avalon_streaming start
set_interface_property l_audio_streaming_source associatedClock audio_clock
set_interface_property l_audio_streaming_source associatedReset audio_reset
set_interface_property l_audio_streaming_source dataBitsPerSymbol 8
set_interface_property l_audio_streaming_source errorDescriptor ""
set_interface_property l_audio_streaming_source firstSymbolInHighOrderBits true
set_interface_property l_audio_streaming_source maxChannel 0
set_interface_property l_audio_streaming_source readyLatency 0
set_interface_property l_audio_streaming_source ENABLED true
set_interface_property l_audio_streaming_source EXPORT_OF ""
set_interface_property l_audio_streaming_source PORT_NAME_MAP ""
set_interface_property l_audio_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property l_audio_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port l_audio_streaming_source l_audio_ready ready Input 1
add_interface_port l_audio_streaming_source l_audio_data data Output 16
add_interface_port l_audio_streaming_source l_audio_valid valid Output 1


# 
# connection point r_audio_streaming_source
# 
add_interface r_audio_streaming_source avalon_streaming start
set_interface_property r_audio_streaming_source associatedClock audio_clock
set_interface_property r_audio_streaming_source associatedReset audio_reset
set_interface_property r_audio_streaming_source dataBitsPerSymbol 8
set_interface_property r_audio_streaming_source errorDescriptor ""
set_interface_property r_audio_streaming_source firstSymbolInHighOrderBits true
set_interface_property r_audio_streaming_source maxChannel 0
set_interface_property r_audio_streaming_source readyLatency 0
set_interface_property r_audio_streaming_source ENABLED true
set_interface_property r_audio_streaming_source EXPORT_OF ""
set_interface_property r_audio_streaming_source PORT_NAME_MAP ""
set_interface_property r_audio_streaming_source CMSIS_SVD_VARIABLES ""
set_interface_property r_audio_streaming_source SVD_ADDRESS_GROUP ""

add_interface_port r_audio_streaming_source r_audio_data data Output 16
add_interface_port r_audio_streaming_source r_audio_ready ready Input 1
add_interface_port r_audio_streaming_source r_audio_valid valid Output 1


# 
# connection point SDRAM_avalon_master
# 
add_interface SDRAM_avalon_master avalon start
set_interface_property SDRAM_avalon_master addressUnits SYMBOLS
set_interface_property SDRAM_avalon_master associatedClock clock
set_interface_property SDRAM_avalon_master associatedReset reset
set_interface_property SDRAM_avalon_master bitsPerSymbol 8
set_interface_property SDRAM_avalon_master burstOnBurstBoundariesOnly false
set_interface_property SDRAM_avalon_master burstcountUnits WORDS
set_interface_property SDRAM_avalon_master doStreamReads false
set_interface_property SDRAM_avalon_master doStreamWrites false
set_interface_property SDRAM_avalon_master holdTime 0
set_interface_property SDRAM_avalon_master linewrapBursts false
set_interface_property SDRAM_avalon_master maximumPendingReadTransactions 1
set_interface_property SDRAM_avalon_master maximumPendingWriteTransactions 0
set_interface_property SDRAM_avalon_master readLatency 0
set_interface_property SDRAM_avalon_master readWaitTime 1
set_interface_property SDRAM_avalon_master setupTime 0
set_interface_property SDRAM_avalon_master timingUnits Cycles
set_interface_property SDRAM_avalon_master writeWaitTime 0
set_interface_property SDRAM_avalon_master ENABLED true
set_interface_property SDRAM_avalon_master EXPORT_OF ""
set_interface_property SDRAM_avalon_master PORT_NAME_MAP ""
set_interface_property SDRAM_avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property SDRAM_avalon_master SVD_ADDRESS_GROUP ""

add_interface_port SDRAM_avalon_master sdram_addr address Output 26
add_interface_port SDRAM_avalon_master sdram_byteenable_n byteenable_n Output 2
add_interface_port SDRAM_avalon_master sdram_chipselect chipselect Output 1
add_interface_port SDRAM_avalon_master sdram_writedata writedata Output 16
add_interface_port SDRAM_avalon_master sdram_read_n read_n Output 1
add_interface_port SDRAM_avalon_master sdram_write_n write_n Output 1
add_interface_port SDRAM_avalon_master sdram_readdata readdata Input 16
add_interface_port SDRAM_avalon_master sdram_readdata_valid readdatavalid Input 1
add_interface_port SDRAM_avalon_master sdram_waitrequest waitrequest Input 1

